name: 🧪 CI

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build-prod
      - uses: actions/upload-artifact@v4
        with:
          path: out/index.html
          retention-days: 1
  test:
    name: 🔬 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
  check-filenames:
    name: 📝 Check Filenames
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let files = [];
            if (context.eventName === 'pull_request') {
              files = await github.paginate(
                github.rest.pulls.listFiles,
                { owner: context.repo.owner, repo: context.repo.repo, pull_number: context.issue.number, per_page: 100 }
              );
            } else if (context.eventName === 'push') {
              const commits = context.payload.commits || [];
              const filenames = new Set();
              for (const commit of commits) {
                for (const file of [...(commit.added || []), ...(commit.modified || []), ...(commit.renamed || [])]) {
                  filenames.add(file);
                }
              }
              files = Array.from(filenames).map(filename => ({ filename, status: 'added' }));
            }

            const invalidFiles = files
              .filter(({ status }) => status !== 'removed')
              .map(({ filename }) => filename)
              .filter(filename => /[^\x00-\x7F]/.test(filename));

            if (invalidFiles.length > 0) {
              core.setFailed(`❌ The following files contain Unicode characters:\n${invalidFiles.join('\n')}`);
            } else {
              core.info('✅ All new/modified filenames are ASCII-only');
            }
  eslint:
    name: 🔍 ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx eslint --format gha

  prettier:
    name: 🎨 Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx prettier --check .
