name: 🚀 Deploy

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - prod
          - staging
      target_host:
        description: "Deployment Host"
        required: true
        default: "staging"
        type: choice
        options:
          - eu
          - us
          - staging
      target_subdomain:
        description: "Deployment Subdomain"
        required: false
        default: ""
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.target_environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST_STAGING }} >> ~/.ssh/known_hosts
          cat >.env.${{ inputs.target_environment }} <<EOF
          ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}
          CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          DOCKER_REPO=${{ vars.DOCKERHUB_REPO }}
          DOCKER_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          DOMAIN=${{ vars.DOMAIN }}
          MON_PASSWORD=${{ secrets.MON_PASSWORD }}
          MON_USERNAME=${{ secrets.MON_USERNAME }}
          R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}
          R2_BUCKET=${{ secrets.R2_BUCKET }}
          R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
          SERVER_HOST_STAGING=${{ secrets.SERVER_HOST_STAGING }}
          SERVER_HOST_US=${{ secrets.SERVER_HOST_US }}
          SERVER_HOST_EU=${{ secrets.SERVER_HOST_EU }}
          SSH_KEY=~/.ssh/id_rsa
          VERSION_TAG="latest"
          EOF
          ./deploy.sh ${{ inputs.target_environment }} ${{ inputs.target_host }} ${{ inputs.target_subdomain }}
