name: Check lang_code matches filename

on: [push, pull_request]

jobs:
  lang-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check lang_code matches filename
        run: |
          shopt -s nullglob
          files=(resources/lang/*.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No resources/lang/*.json files found. Skipping check."
            exit 0
          fi
          for f in "${files[@]}"; do
            name=$(basename "$f" .json)
            code=$(jq -r '.lang.lang_code' "$f")
            if [ "$name" != "$code" ]; then
              echo "❌ $f: lang_code ($code) does not match filename ($name)"
              exit 1
            fi
          done
          echo "✅ All lang_code values match their filenames!"
